name: CI

on:
  push:
    branches:
      - main
jobs:
  backend:
    phases:
      build:
        commands:
          - '# Execute Amplify CLI with the helper script'
          - amplifyPush --simple
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Dependencies
        run: yarn
      - name: Test
        run: yarn test:ci --verbose
      - run: yarn policies set-version 1.22.17
      - run: yarn install --frozen-lockfile
      - run: expo publish --non-interactive
