name: CI

on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-1
      AWS_DEFAULT_OUTPUT: json
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: ./scripts/amplify-deploy.sh noms master
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Dependencies
        run: yarn
      - name: Test
        run: yarn test:ci --verbose
      - run: yarn policies set-version 1.22.17
      - run: yarn install --frozen-lockfile
      - run: expo publish --non-interactive
